version: "3.9"
services:
  ssi-core-dev-env:
    build: .
    volumes:
    - ./data:/app/data
    entrypoint: /app/bin/waltid-ssi-kit serve -b 0.0.0.0
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
