name: Snapshot release workflow for walt.id SSI Kit

on:
  push:
    branches:
      - master

jobs:
  verify-wrapper:
    name: "Verification"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

  gradle:
    needs: verify-wrapper
    name: "Build"
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt-hotspot'
          java-version: '16'
      - name: Running gradle build
        uses: eskatos/gradle-command-action@v1.3.3
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        with:
          arguments: build publish --no-daemon
      - name: Docker Build and Push SNAPSHOT
        uses: philpotisk/github-action-docker-build-push@master
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_FILE: Dockerfile
          CONTAINER_TAG: waltid/ssikit:latest
      - name: Continuous deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: docker rm $(docker stop $(docker ps -a -q --filter ancestor=waltid/ssikit:latest --format="{{.ID}}")); docker pull waltid/ssikit:latest && docker container run -p 7000-7004:7000-7004 -itdv $(pwd)/data:/app/data docker.io/waltid/ssikit:latest serve -b 0.0.0.0
